name: 'GitHub Vault Action'
description: 'Setup Vault Authentication for GitHub Actions'
inputs:
  secrets:
    description: 'Secrets to be fetched from Vault'
    required: false
  platform:
    description: 'Qumulus platform to be used'
    required: true
  region:
    description: 'AWS Region - either primary or secondary'
    required: false
    default: 'primary'
  export_token:
    description: 'Export vault Token to the environment'
    required: false
    default: 'true'
  vault_addr:
    description: 'Vault Address'
    required: true
  aws_account_data:
    description: 'AWS account data for different environments'
    required: false
runs:
  using: "composite"
  steps:
    - name: Set Variables
      shell: bash
      env:
        VAULT_ADDR: ${{ inputs.vault_addr }}
      run: |
        if [ "$GITHUB_EVENT_NAME" == "delete" ]; then
          BRANCH=${{ github.event.ref }}
        else
          BRANCH=${{ github.base_ref || github.ref_name }}
        fi
        VAULT_OIDC_BRANCH=$BRANCH
        if [ "$BRANCH" != "main" ] && [ "$BRANCH" != "staging" ] && [ "$BRANCH" != "qa" ]; then
          VAULT_OIDC_BRANCH=dev
        fi
        if [ "$BRANCH" == "main" ]; then
          ENVIRONMENT=prod
        elif [ "$BRANCH" == "qa" ] || [ "$BRANCH" == "staging" ]; then
          ENVIRONMENT=$BRANCH
        else
          ENVIRONMENT=dev
        fi
        REPOSITORY=$(echo ${GITHUB_REPOSITORY#*/})
        ROLE="github-qcp-${REPOSITORY}-${VAULT_OIDC_BRANCH}"
        if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
          ROLE="${ROLE}-pr"
        fi
        echo "ROLE=$ROLE" >> $GITHUB_ENV
        echo "VAULT_ADDR=$VAULT_ADDR" >> $GITHUB_ENV
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
        echo "VAULT_ADDR=${VAULT_ADDR}" >> $GITHUB_ENV
        echo "ENVIRONMENT=${ENVIRONMENT}" >> $GITHUB_ENV

    - name: Import Secrets
      id: import-secrets
      uses: hashicorp/vault-action@v3
      with:
        exportToken: ${{ inputs.export_token }}
        method: jwt
        url: ${{ inputs.VAULT_ADDR }}
        path: jwt/github
        role: ${{ env.ROLE }}
        secrets: ${{ inputs.secrets }}

    - name: Set up AWS Profiles and Environment Variables
      shell: bash
      env:
        AWS_ACCOUNT_DATA_BASE64: ${{ inputs.aws_account_data }}
        PLATFORM: ${{ inputs.platform }}
        REGION: ${{ inputs.region }}
      run: |

        mkdir ~/.aws
        AWS_CONFIG_PATH=~/.aws/config
        AWS_ACCOUNT_DATA=$(echo $AWS_ACCOUNT_DATA_BASE64 | base64 -d | jq ".${PLATFORM}.${BRANCH}")
        AWS_ACCOUNT_DATA_REGIONAL=$(echo $AWS_ACCOUNT_DATA_BASE64 | base64 -d | jq ".${PLATFORM}.${BRANCH}.${REGION}")

        for s in $(echo $AWS_ACCOUNT_DATA_REGIONAL | jq -r "to_entries|map(\"AWS_\(.key | ascii_upcase)=\(.value|tostring)\")|.[]" ); do
            export $s
        done

        export "AWS_ACCOUNT_ID=$(echo $AWS_ACCOUNT_DATA | jq -r '.account_id')" >> $GITHUB_ENV
        export "AWS_DOMAIN_HOSTED_ZONE_ID=$(echo $AWS_ACCOUNT_DATA | jq -r '.hosted_zone_id')" >> $GITHUB_ENV
        export "DOMAIN_NAME=$(echo $AWS_ACCOUNT_DATA | jq -r '.domain_name')" >> $GITHUB_ENV
        export "AWS_REGION=$(echo $AWS_ACCOUNT_DATA_REGIONAL | jq -r '.region')" >> $GITHUB_ENV

        echo "[default]" > $AWS_CONFIG_PATH
        echo "region = ${AWS_REGION}" >> $AWS_CONFIG_PATH
        echo "credential_process=vault-aws-credential-helper ${AWS_REGION} github-${REPOSITORY}-${BRANCH} ${AWS_ACCOUNT_ID} vault/github/github-${REPOSITORY}-${BRANCH}" >>  $AWS_CONFIG_PATH
        echo "" >> $AWS_CONFIG_PATH

        for p in $(echo $AWS_ACCOUNT_DATA_BASE64 | base64 -d | jq -r "to_entries | .[] | .key"); do
            for b in $(echo $AWS_ACCOUNT_DATA_BASE64 | base64 -d | jq -r ".${p} | to_entries | .[] | .key"); do

                account_id=$(echo $AWS_ACCOUNT_DATA_BASE64 | base64 -d | jq -r ".${p}.${b}.account_id")

                echo "[profile ${p}_${b}]" >> $AWS_CONFIG_PATH
                echo "region = ${AWS_REGION}" >> $AWS_CONFIG_PATH
                echo "credential_process=vault-aws-credential-helper ${AWS_REGION} github-${REPOSITORY}-${BRANCH} ${account_id} vault/github/github-${REPOSITORY}-${BRANCH}" >>  $AWS_CONFIG_PATH
                echo "" >> $AWS_CONFIG_PATH

            done
        done
